name: deploy-manifests

on:
  push:
    branches: 
      - master
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} 
      - run: doctl kubernetes cluster kubeconfig save k8s-1-18-8-do-1-sfo2-1602887650476
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
